#colors support
set-option -sa terminal-overrides ",xterm*.Tc"
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# set preffix key to ctrl + space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

#enable mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g @tokyo-night-tmux_transparent 1

#tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'

run  '~/.tmux/plugins/tpm/tpm'
